services:
  coffee-shop:
    build: .
    image: coffee-shop:latest
    container_name: coffee-shop-app
    restart: unless-stopped
    ports:
      - "80:5000"
    volumes:
      # 持久化数据库
      - coffee_data:/app/data
      # 持久化上传文件
      - coffee_uploads:/app/server/uploads
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_PATH=/app/data/database.sqlite
      - JWT_SECRET=coffee-shop-jwt-secret-key-2025
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - coffee-network

  # 可选：添加 Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: coffee-shop-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - coffee-shop
    networks:
      - coffee-network
    profiles:
      - nginx

volumes:
  coffee_data:
    driver: local
  coffee_uploads:
    driver: local

networks:
  coffee-network:
    driver: bridge 